version: "3.7"

services:
  db:
    image: postgres
    container_name: docker-postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432

  backend:
    build: backend/
    image: moneyback
    container_name: backend
    restart: always
    ports:
      - ${NODE_PORT}:8080
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      NODE_ENV: ${NODE_ENV}
      NODE_PORT: ${POSTGRES_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

volumes:
  db-data: